### ISSUE TITLE
Trying out and errors in anchor-plugin

### ISSUE THREAD

**Issue by rakeden** [wharfkit/example-vite-vue-ts#1]
Hello there,

interested in trying out so I cloned repo. After installing packages and running the dev script I encountered the following errors in development and usage.

**Note: This work for the CloudWalletPlugin, but not AnchorWalletPlugin**

My setup:
- node v16.13.1 && v18.14.0
- no mods to repo
- Anchor Wallet v1.3.9
- typescript v5.0.3

How to reproduce:
- `npm install`
- `npm run dev`
- `load page`

**Error reporting**

_when Page is loaded_

<img width="673" alt="Screenshot 2023-04-04 at 17 00 56" src="https://user-images.githubusercontent.com/5896201/229834500-1b948751-a52e-4080-b60b-fa48a07028c8.png">

_when Anchor opens to sign in any of my wallets_

<img width="673" alt="Screenshot 2023-04-04 at 17 10 37" src="https://user-images.githubusercontent.com/5896201/229837560-c9643073-2382-4dba-aff5-edea2c2ad751.png">

**Comment by aaroncox** [comment]
For the `Either a RestoreArgs object or a Storage instance...` error, that's something we'll track/fix in https://github.com/wharfkit/session/issues/42.

For the second error involving Anchor, we'll look into that. I'm not sure why the callback wouldn't be returning all that data properly. It was working when I originally set this repo up, and oddly enough I'm using the same version of Anchor as you.

**Comment by aaroncox** [comment]
How was the account setup in Anchor, if you remember? Was it an "Import by Private Key" or something manually setup?

We've tried with multiple people on 1.3.9 to try and reproduce this issue - but can't for whatever reason, and are trying to figure out what might be different between the accounts we have loaded up and the ones you're encountering this issue with.

**Comment by rakeden** [comment]
Tested now with multiple wallets on Anchor, same error everywhere.
Created a new keypair and wallet from **inside** Anchor with same result.

Same error on Anchor Mobile after debugging via iPhone and Safari Console. It's stuck when pressing the "Login" button for a few seconds and skips to the home screen of Anchor Mobile instead of returning to my browser.
Users isn't logged in when checking the browser.

This works fine on Wharkit CloudWalletPlugin on all tested devices.

Side Note: Tested UAL & UAL-Anchor and those accounts login like they should.

Hope that's helpful. Let me know which additional information you might need!

**Comment by rakeden** [comment]
Tested standalone wharfkit/web-ui-render and repo to confirm this issue.

**Comment by aaroncox** [comment]
Oh very interesting... strange that it's happening across all versions of the wallet. There's gotta be a bug somewhere and its very strange we're not seeing the same thing. 

Do you have a repo with this test code setup you created? I'm wondering if we run your code, we'll see the same thing.

**Comment by aaroncox** [comment]
> Tested standalone wharfkit/web-ui-render and repo to confirm this issue.

I should have read this first 😂 

So its happening when you try to log in to this as well? https://ui-test.wharfkit.com/#login

**Comment by rakeden** [comment]
So, tested a bit, even on a second device and found something.
Managed to reproduce it now: It's related to the Checkbox for the Session for later usage.

<img width="353" alt="Screenshot 2023-04-06 at 12 13 54" src="https://user-images.githubusercontent.com/5896201/230347723-925af3b3-5983-48c7-a113-d6d2c488eadb.png">

When toggled OFF, the login doesn't work and console prints the following errors

<img width="848" alt="Screenshot 2023-04-06 at 12 17 41" src="https://user-images.githubusercontent.com/5896201/230348644-6af4ada6-523b-4919-853d-7e07ec24cdde.png">

As soon as I toggle the checkbox ON I can sign in on any of the test pages!

Can you please check and possibly confirm this on your end?

**Comment by aaroncox** [comment]
Interesting - yeah I think that'd do it. We probably need to remove that option from Anchor Desktop all together, it's a legacy thing that really no one should use anymore. The plugin wasn't expecting that to turn on/off 😅 

You did however mention this was happening on mobile too? Mobile shouldn't have that option, and should always establish a session by default.

**Comment by aaroncox** [comment]
Users as of Anchor Desktop 1.3.12 no longer have the option to disable the "Create a Session for future usage...", so moving forward this shouldn't be an issue.

If you're still experiencing other issues with mobile - feel free to open a new issue!
